apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: metlo-cluster
  region: ap-southeast-1
  version: "1.20"

managedNodeGroups:
  - name: metlo-node
    minSize: 0
    maxSize: 3
    instanceType: t3.xlarge
    amiFamily: Ubuntu2004
    volumeSize: 30
    volumeEncrypted: true
    desiredCapacity: 1